### ISSUE TITLE
[Error] Algorithm of Date_Utility

### ISSUE THREAD

**Issue by quocdat-le-insacvl** [danymat/INSAnonym-utils#83]
#### Issue description
Hi, I found that [the code to calculate Date_Utility ](https://github.com/danymat/INSAnonym-utils/blob/main/metrics/dateUtil.py) doesn't give the result that it's expected to be. 
According to the documentation,
 "**This metric consist in calculating the difference of days of each row between the original and anonymized dataframe.**"

1. For example, we have an anonymized row with date=2015-02-01 and the original with date=2015-01-31. I think that in this case the difference is 1 day, make more sense than it was 30 days.
2. In addition, the code doesn't take into consideration that the lowest score of each line is 0. (now it can be negative)

#### Input 

![image](https://user-images.githubusercontent.com/71183203/140570659-a3bcaf7a-e8b0-4e53-b920-d4852ee84ed4.png)

![image](https://user-images.githubusercontent.com/71183203/140570725-e771625e-7516-448e-ab9c-7d436d1bb656.png)

#### Output

![image](https://user-images.githubusercontent.com/71183203/140570800-4179c36f-fed7-430d-9196-26842caad1d7.png)

**Comment by danymat** [comment]
> For example, we have an anonymized row with date=2015-02-01 and the original with date=2015-01-31. I think that in this case the difference is 1 day, make more sense than it was 30 days.

Indeed you're right. 

I don't know if I will have time to fix it very soon though. You can try making a PR to fix this bug, I will take the time to review it.
If you're going the competition as of now, and we can't update the server on schedule (pinged @beng-git), I think you'll have to be careful of this bug when doing your anonymization.

> In addition, the code doesn't take into consideration that the lowest score of each line is 0. (now it can be negative)

I think @zinebhit did provide a similar fix for an other metric (https://github.com/danymat/INSAnonym-utils/pull/81). You can try doing the same check and create a PR for it, should be pretty easy to do.
